[firebase]
<<<<<<< HEAD
pass_key = "components\\water-quality-prediction-65f06-firebase-adminsdk-jxitc-bd6157a1fd.json"
=======
pass_key = "water-quality-prediction-65f06-firebase-adminsdk-jxitc-bd6157a1fd.json"
>>>>>>> 1c537cb3978f4e8791021fd02cc9aabca9c3196c
